/*AT COMMANDS*/
export enum ENM_AT_COMMANDS {
    AT_SAVE_SETTINGS = 'AT+SAVESETTINGS',
    AT_JSON_SETTINGS = 'AT+JSONSETTINGS',
    AT_JSON_STATUS = 'AT+JSONSTATUS',
    AT_FACTORY_RESET = 'AT+FACTORYRESET',
    AT_DEVICE_TYPE = 'AT+DEVICETYPE',
};

/*AT COMMANDS PER DEVICE TYPE - USED BY TERMINAL TO PERFORM AUTOCOMPLETE*/
export const AT_COMMANDS_LIST = ['AT', 'AT+RADIODEVICEID', 'AT+RADIOOUTPWR', 'AT+RADIOMSGSIGNATURE', 'AT+RADIOKEEPALIVETIMEOUT', 'AT+SENSORMEASUREMENTTIMEOUT', 
'AT+ECHO', 'AT+JSONSETTINGS', 'AT+VERSION', 'AT+UID', 'AT+DEVICETYPE', 'AT+SAVESETTINGS', 'AT+FACTORYRESET', 'AT+USAGE', 'AT+SENSORVALUES', 'AT+STATUS', 'AT+JSONSTATUS',
'AT+RADIOSERVERID', 'AT+RADIOMAXRETRIES', 'AT+APIHOSTNAME', 'AT+APIAUTHORIZATION', 'AT+APIURI', 'AT+APIPORT', 'AT+APICLIENTID', 'AT+APIKEEPALIVETIMEOUT', 'AT+APSSID', 'AT+APKEY'];

/*SERIAL PORT OBSERVABLE*/
export enum ENM_SERIAL_PORT_EVENT {
    SERIAL_CONNECT = 1,
    SERIAL_DISCONNECT = 2,
    SERIAL_PAYLOAD = 3
}

/*WEB-USB devices filter*/
export const WEB_USB_DEVICES_FILTER = [{ vendorId: 0x2886, productId: 0x802F }];

export enum ENM_CONNECTION_STATUS {
    DISCONNECTED,
    CONNECTED_SIMPLE_SENSOR,
    CONNECTED_BRIDGE_SERVER_SENSOR,
    CONNECTED_UNKNOWN,
    CONNECTED_ERROR
};

export enum ENM_DEVICES_TYPE {
    SIMPLE_SENSOR = 'SIMPLE-SENSOR',
    BRIDGE_SERVER_SENSOR ='BRIDGE-SERVER-SENSOR',
    UNKNOWN = ''
}